#!/bin/sh
ulimit -c 0
total=0
pathsize=`/usr/bin/du -s --block-size=1 /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details --exclude=group | awk '{print $1}'`
total=$(($total+$pathsize))
group=0
group=`/usr/bin/du -s --block-size=1 /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/group | awk '{print $1}'`
echo $group > /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/group/duse_group.tmp && \
mv /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/group/duse_group.tmp /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/group/duse_group
pathsize=`/usr/bin/du -s --block-size=1 /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/msrv32_top.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/duse_manager_res.tmp && \
mv /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/duse_manager_res.tmp /home/WBPD04/JashtiG/VLSI_PD/Fusion_compiler_labs/FC_LABS_handsOn/Macro_projects/RISC/icvDRC_run/run_details/duse_manager_res
